<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ScreenTextCatcher.Core\ScreenTextCatcher.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\*.ico" />
    <Resource Include="Assets\*.png" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Assets\*.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\*.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
    <Version>1.2.2</Version>
  </PropertyGroup>

</Project>
